package Unblock::WebSocket::Client;

use strict;
use warnings;
use parent 'Unblock::WebSocket::_Engine';

sub new {
    my ($class, %option) = @_;
    return $class->_new(role => 'client', %option);
}

1;

__END__

=head1 NAME

Unblock::WebSocket::Client - established client-side WebSocket protocol engine

=head1 SYNOPSIS

    my $ws = Unblock::WebSocket::Client->new(
        on_message => sub {
            my ($ws, $payload, $type) = @_;
        },
    );

    $ws->input($bytes_from_transport);
    $ws->send_text('hello');

    while ($ws->want_write) {
        $transport->write($ws->output);
    }

=head1 DESCRIPTION

This object owns established client-side WebSocket protocol state.

It does not connect a socket, perform TLS, perform the opening HTTP handshake,
or run an event loop.

Normally it is created after
L<Unblock::WebSocket::Handshake/connection_options> has validated the HTTP
response:

    my $ws = Unblock::WebSocket::Client->new(
        %{ $handshake->connection_options },
        on_message => sub { ... },
    );

When RFC 7692 was negotiated, those options carry the permessage-deflate state
needed by the established connection.

=head1 TRANSPORT MODEL

Feed bytes from the transport with C<input()>.

Drain generated bytes with C<output()> while C<want_write()> is true.

Call C<input_eof()> when the transport closes.

The object never reads or writes a socket itself.

=cut
