package Unblock::WebSocket::Server;

use strict;
use warnings;
use parent 'Unblock::WebSocket::_Engine';

sub new {
    my ($class, %option) = @_;
    return $class->_new(role => 'server', %option);
}

1;

__END__

=head1 NAME

Unblock::WebSocket::Server - established server-side WebSocket protocol engine

=head1 SYNOPSIS

    my $ws = Unblock::WebSocket::Server->new(
        on_message => sub {
            my ($ws, $payload, $type) = @_;
        },
    );

    $ws->input($bytes_from_transport);

    while ($ws->want_write) {
        $transport->write($ws->output);
    }

=head1 DESCRIPTION

This object owns established server-side WebSocket protocol state.

It does not own a listener, socket, TLS connection, HTTP server, timer, or event
loop.

Normally it is created after
L<Unblock::WebSocket::Handshake/server_accept> validates the opening request:

    my $ws = Unblock::WebSocket::Server->new(
        %{ $handshake->connection_options },
        on_message => sub { ... },
    );

When RFC 7692 was negotiated, those options carry the permessage-deflate state
needed by the established connection.

=head1 TRANSPORT MODEL

Feed established WebSocket bytes with C<input()>.

Drain generated bytes with C<output()> while C<want_write()> is true.

Call C<input_eof()> when the transport closes.

The object never reads or writes a socket itself.

=cut
