package Unblock::WebSocket::Server;

use strict;
use warnings;
use parent 'Unblock::WebSocket::_Engine';

sub new {
    my ($class, %option) = @_;
    return $class->_new(role => 'server', %option);
}

1;

__END__

=head1 NAME

Unblock::WebSocket::Server - established server-side WebSocket protocol engine

=head1 DESCRIPTION

This object owns WebSocket protocol state only. Feed it bytes from an already
established WebSocket stream and drain generated bytes with C<output()>.

=cut
