package Unblock::WebSocket;

use strict;
use warnings;

our $VERSION = '0.01';
our $NATIVE_AVAILABLE = eval {
    require XSLoader;
    XSLoader::load(__PACKAGE__, $VERSION);
    1;
} ? 1 : 0;

sub native_available { $NATIVE_AVAILABLE }

1;

__END__

=head1 NAME

Unblock::WebSocket - event-loop and platform neutral WebSocket protocol engine

=head1 DESCRIPTION

Unblock::WebSocket provides WebSocket protocol handling without owning sockets,
TLS, DNS, timers, or an event loop.

Use L<Unblock::WebSocket::Handshake> for the opening HTTP handshake.

Use L<Unblock::WebSocket::Client> or L<Unblock::WebSocket::Server> after the
WebSocket stream has been established.

The distribution supports:

=over

=item * RFC 6455 framing, masking, fragmentation, Ping/Pong, Close, and UTF-8

=item * HTTP/1.1 Upgrade handshakes

=item * HTTP/2 and HTTP/3 Extended CONNECT handshakes

=item * RFC 7692 permessage-deflate

=item * a portable Perl protocol backend

=item * a private native backend for faster framing and masking

=back

The public protocol API remains bytes in and bytes out. Applications do not
need to work with WebSocket frame objects.

=head1 NATIVE BACKEND

C<native_available()> reports whether the optional XS backend loaded.

When available, normal established connections use the native backend unless a
portable-only option requires otherwise. This is an implementation detail; the
public Client and Server APIs are the same.

=head1 ESTABLISHED CONNECTION API

L<Unblock::WebSocket::Client> and L<Unblock::WebSocket::Server> share the same
established-connection API.

Common constructor options include:

=over

=item C<max_message_size>

Maximum decompressed application message size. The default is 16 MiB.

=item C<high_water>

Output high-water mark. The default is 65536 bytes.

=item C<low_water>

Output low-water mark. The default is 32768 bytes.

=item C<permessage_deflate>

Negotiated RFC 7692 parameters. Normally this comes from
L<Unblock::WebSocket::Handshake/connection_options>.

=item C<backend>

C<native> or C<perl>. Normal applications should let the module choose
automatically. This option is mainly useful for differential testing and
debugging.

=back

Callbacks are supplied to the constructor:

=over

=item C<on_message>

    on_message => sub {
        my ($ws, $payload, $type) = @_;
    }

C<$type> is C<text> or C<binary>.

=item C<on_ping>

Called for received Ping payloads. The protocol engine also sends the required
Pong automatically.

=item C<on_pong>

Called for received Pong payloads.

=item C<on_close>

    on_close => sub {
        my ($ws, $code, $reason) = @_;
    }

Called when a Close frame is received. A transport EOF without a Close frame
reports an undefined code and C<transport EOF> as the reason.

=item C<on_error>

Called for protocol or callback errors.

=item C<on_drain>

Called after buffered output falls back to or below C<low_water> after reaching
the high-water state.

=back

Common methods include:

=over

=item C<input($bytes)>

Feed bytes received from the ordered transport.

=item C<input_eof()>

Report transport EOF.

=item C<output([$maximum])>

Remove and return generated transport bytes. An optional positive maximum limits
the returned chunk size.

=item C<want_write()>

True while generated output is waiting to be drained.

=item C<want_read()>

True while the protocol engine can still accept transport input.

=item C<output_size()>

Number of generated bytes currently buffered.

=item C<send_text($text)>

Queue one text message.

=item C<send_binary($bytes)>

Queue one binary message.

=item C<ping([$payload])>

Queue a Ping control frame. Payloads are limited to 125 bytes.

=item C<close(%options)>

Begin a normal WebSocket Close handshake. C<code> defaults to 1000 and
C<reason> is optional.

=item C<abort()>

Stop the protocol engine immediately and discard buffered output.

=item C<is_open()>, C<is_closing()>, C<is_closed()>

Inspect connection state.

=item C<close_sent()>, C<close_received()>, C<close_complete()>

Inspect the Close handshake.

=item C<want_end()>

True when the transport may be ended after pending output is drained.

=item C<backend()>

Returns C<native> or C<perl>.

=item C<permessage_deflate()>

Returns the negotiated compression parameters, or undef.

=back

C<send_text()>, C<send_binary()>, and C<ping()> accept their bytes even when
the output high-water mark is reached. A false return means the producer should
pause until C<on_drain> runs.

=head1 LICENSE

MIT License.

=cut
